COLUMN_DESCRIPTIONS =   {"NAME": "brand + model name of the basketball shoe",
                        "30 SEC HEATING (F) (INTERNAL)" : "internal temperature after 30 seconds of heating, indicating breathability or ventilation",
                        'BOUNCE HEIGHT AVERAGE (cm)': "average bounce height on the midsole",
                        'HEEL HEIGHT (cm)': "height of the heel from the ground",
                        'FOREFOOT HEIGHT (cm)': "height of the forefoot from the ground, lower indicating more court feeling",
                        'HEEL-BALL DROP (cm)': "difference in height between heel and forefoot of the basketball shoe, higher indicating more achilles relief but less court feel",
                        "WEIGHT oz (US MEN'S 11)": "weight of the basketball shoe in ounces",
                        'DEGREE OF SLIP': "angle of incline at which the basketball shoe begins to slip", 
                        'SHANK SCORE': "score based on the shank material and design for torsional stability",
                        'SPEED RATIO': "ratio of speed given the bounce height, weight and shank",
                        'DUROMETER': "durometer score indicating the hardness of the outsole",
                        'LAST SHAPE (DEGREE OF INFLARE)': "degree of inflare of the last shape",
                        'LENGTH (cm)': "outsole length given the same size",
                        'METATARSAL WIDTH(cm)': "width of the basketball shoe at the metatarsal area",
                        'TOEBOX WIDTH(cm)': "width of the basketball shoe at the toe box",
                        # 'TOE BOX TAPER (DEGREES)': "angle of tapering of the toe box",
                        # 'RESTING POSITION (DEGREES OF EVERSION)': "angle of the basketball shoe when at rest, indicating how much it rolls outward",
                        # 'LOADED POSITION (DEGREES OF EVERSION)': "angle of the basketball shoe when loaded, indicating how much it rolls outward under weight",
                        # 'HEEL WIDTH (cm)': "width of the basketball shoe at the heel",
                        # 'NARROWEST MIDFOOT MEASUREMENT (cm)': "narrowest width of the midfoot",
                        'OVERALL RATING SCORE': "overall rating score based on various performance metrics out of 40",
                        'MIDSOLE FOAM': "type of midsole foam used in the basketball shoe",
                        'SHANK MATERIAL': "material used for the shank of the basketball shoe",
                        # 'UPPER DURABILITY 0 = NOT THROUGH 1ST LAYER 1 = THROUGH 1ST LAYER':,
                        # 'OUTSOLE DURABILITY':, 
                        'CONTAINMENT': "how well the basketball shoe contains the foot during movement out of 5",
                        'BOUNCE': "bounce score indicating the responsiveness of the basketball shoe out of 5",
                        'SHOCK ABSORPTION': "shock absorption score indicating how well the basketball shoe absorbs impact out of 5",
                        'SPEED': "speed score indicating how fast the basketball shoe can perform out of 5",
                        'DURABILITY': "durability score indicating how long the basketball shoe lasts out of 5",
                        'COMFORT': "comfort score indicating how comfortable the basketball shoe is to wear out of 5",
                        'SUPPORT': "support score indicating how well the basketball shoe supports the foot out of 5",
                        'PLAYABILITY': "playability score indicating how versatile the basketball shoe is for different types of play out of 5",
                        'FITS ORTHOTICS': "boolean indicating if the basketball shoe fits orthotics",
                        'FLAT ARCH': "boolean indicating if the basketball shoe is designed for flat arches",
                        'NEUTRAL ARCH': "boolean indicating if the basketball shoe is designed for neutral arches",
                        'HIGH ARCH': "boolean indicating if the basketball shoe is designed for high arches",
                        'HARDWOOD SURFACE': "boolean indicating if the basketball shoe is suitable for hardwood surfaces",
                        'RUBBERIZED SURFACE': "boolean indicating if the basketball shoe is suitable for rubberized surfaces",
                        'ASPHALT SURFACE': "boolean indicating if the basketball shoe is suitable for outdoor asphalt surfaces"}